---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ipwhitelist
  namespace: dalai
spec:
  ipWhiteList:
   sourceRange:
     - 165.225.76.229
     - 165.225.76.244
     - 81.185.164.229
     - 92.184.100.202
     - 91.170.182.6
     - 165.225.20.222

